format_version: 10
pipelines:
  git-learning:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-38f2afa:
        git: https://github.com/romaryoricardo/learning-git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-app:
            timeout: 0
            environment_variables:
              NAME: Romaryo
            tasks:
            - exec:
                arguments:
                - Build ${NAME}
                command: echo
                run_if: passed
