format_version: 10
pipelines:
  MyPipe:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c19ba43:
        git: https://github.com/romaryoricardo/learning-git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Prod:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            secure_variables:
              NAME: AES:b4R6Kpf20x6tFMkPk/5qTw==:lyOzeBHkF25MEFp9kuuXRg==
            tasks:
            - exec:
                arguments:
                - $NAME
                command: echo
                run_if: passed
            - exec:
                arguments:
                - ${$NAME}.txt
                command: touch
                run_if: passed
            - exec:
                arguments:
                - -l
                command: ls
                run_if: passed
